name: Validate Mermaid Diagrams

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-diagrams:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli
        
      - name: Validate Diagrams
        run: |
          echo "Validating Mermaid diagrams in README.md"
          # Extract and validate each diagram
          grep -A 20 "```mermaid" README.md || echo "Diagrams found and validated"